language: node_js
node_js:
- '12'
services:
- docker
notifications:
  email: false
  slack:
    rooms:
      secure: yDQrmDTSMIEFzTFrO4sB0qOLDHRwydQPwrhDvPROhjVKL1uTa96g+RI8SWXMnE5JKVw+6YIJKrSi2FzTZDodlj0ULSeWE+3jvGfaBcUH4wtNG0UJ0tPVczoUOhPSY7nzvC+aSIFzYhVrWPonXSrLCGy5aH6pV1nOaSe1apeRwnjLiQy507HqC6+OXPNxlsHOrsLuC5EUFicuGNQfuGdSRxjrQ2FczaeT/woiHf7UHl7A9GsqO8pQ6M0oM7t8/8iR6x1/v5KlCBz/rCqHdf9+TKSvvxPOeBktiQe9fn4TFvexG7/VHX59cHnR9eqcQYg9tEM6CVblqWmDkewHOhwC/A2RWCB/iVL+5BogaM3gB9DZHcS4Cp7Y5lzycnnVfjmd9KLOmSL2/q62+5pl9+OSfUBf4asmg7ZfW1trQKMSBdkosedjeXCHUZNsOrBaxdMUn63QzlkFcJoWtrZ0SB7Bu78x9Oc/z+SJcXa8ElrxVsIXmysH8R1VtWpwv0g8K7ZKmHgZefLQDGIBKb9bwwqrgsdLaR/ghJMB0R80EAk8yj+obxcWgw8OsKjnq2p7LfIKt6kRaYZIdkk+XGb2HcZZvclu0bgE6XvPXkpEW2ySCrBAcJaup0VOEYsChCKvj7KCOloe1gF1L9W7Pk9oVo/E9zu9x4qkcdTXxZkrCP1Odvs=
    on_success: always
    on_failure: always
script:
- |
  IMAGE_NAME="$TRAVIS_REPO_SLUG"
  if [[ -z "$TRAVIS_TAG" ]]; then
    IMAGE_TAG=latest
    KRAWLER_TAG=latest
  else
    IMAGE_TAG=$(node -p -e "require('./package.json').version")
    KRAWLER_TAG=$(node -p -e "require('./package.json').peerDependencies['@kalisio/krawler']")
  fi
  docker build --build-arg KRAWLER_TAG=$KRAWLER_TAG -f dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
before_script:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push $IMAGE_NAME:$IMAGE_TAG
  on:
    all_branches: true
